### ISSUE TITLE
False negative for re-exports

### ISSUE THREAD

**Issue by jplatte** [davidpdrsn/cargo-public-api-crates#1]
It seems like re-exporting an entire external crate, or individual items of an external crate, leads to `cargo-public-api-crates` not counting those external crates as public API.

Specifically, the [ruma](https://github.com/ruma/ruma/tree/main/crates/ruma) crate passes `cargo public-api-crates check` with an empty `allowed` array.

**Comment by davidpdrsn** [comment]
Good catch! Seems to be because of https://github.com/davidpdrsn/cargo-public-api-crates/blob/main/src/visit.rs#L50
